name: Build

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Set short git commit SHA
        run: echo "app_name=ReTwisted-$( git rev-parse --short ${{ github.sha }} ).exe" >> $GITHUB_ENV
        shell: bash

      - name: Download pip dependencies
        run: pip install -r requirements.txt pyinstaller Pillow

      - name: Build app
        run: |
          python build.py
          mv dist/ReTwisted.exe dist/${{ env.app_name }}

      - name: Calculate SHA256 hash
        working-directory: dist
        run: certutil -hashfile ${{ env.app_name }} SHA256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: "dist/${{ env.app_name }}"
